name: Build and deploy MkDocs to GitHub Pages (docs-dev -> /rj-docs)

# Spouštět při každém pushu (každý commit) do libovolné větve
on:
  push:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Root Node dependencies
        run: npm ci
        working-directory: ${{ github.workspace }}

      - name: Build demo (Vite React)
        run: npm run build:demo
        working-directory: ${{ github.workspace }}

      - name: Build Tailwind CSS for docs
        run: npm run build:css
        working-directory: ${{ github.workspace }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt

      - name: Build MkDocs site
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./site
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
